questions = [
    {
        "question": "Economic regulations are needed for a properly functioning economy.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 10,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Patriotism is important.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 10,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Freedom is more important than order.",
        "effect": {
            "freedom": 10,
            "power": 10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
    {
        "question": "Cultural progress is important.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 10,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "State interventionism in the economy is not real solution to anything.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": -10,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Oligarchy and/or autocracy are/is best form of government.",
        "effect": {
            "freedom": 0,
            "power": -10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Pornography should be banned.",
        "effect": {
            "freedom": -5,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Government should be big.",
        "effect": {
            "freedom": 10,
            "power": 10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 10,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should stop economic globalisation.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": -10,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Free international trade is beneficial to everyone.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 10,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Sometimes protectionist policies are needed.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": -10,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should pursue economic autarky.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": -15,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Income tax should be abolished.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": -10,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should dismantle hierarchies.",
        "effect": {
            "freedom": 0,
            "power": 10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "The state should control all aspects of the economy.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -10,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 15,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Economic organizations should not be international.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": -15,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Healthcare should never be free.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": -10,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Economy should be centrally planned.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -15,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should implement autocracy or despotism.",
        "effect": {
            "freedom": 0,
            "power": -10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Large scale organisations can increase efficiency.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -15,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Ideally laws would not exist.",
        "effect": {
            "freedom": 10,
            "power": 10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should stop or at least reduce immigration.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 10,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "My nation is great.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 10,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "My country should try to regain it's lost territories.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 15,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "International laws are always illegitimate.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": -10,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "World federalism or unity world government is generally good idea.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 15,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Some jobs should be reserved for people born into higher class families.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": -10,
            "commonland": 0
        }
    },
{
        "question": "An individual’s role in society should be inherited from their parents.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": -10,
            "commonland": 0
        }
    },
{
        "question": "Education should be free and universal.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 10,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 10,
            "commonland": 0
        }
    },
{
        "question": "I support isolationist and anti-interventionist policies.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": -10,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Workers should have more say in the workplace.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Market economies are inefficient and undesirable.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should produce based on use not commodity.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "A non monetary economy is desirable.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Prices should be determined by supply and demand.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": -10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Voluntary exchange between individuals should form basis of our economy.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": -10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "AI could help in our economy",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 10,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 10,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Inheritance of anything which is not personal possessions is not legitimate.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 15,
            "commonland": 0
        }
    },
{
        "question": "Some roles should be hereditary.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": -10,
            "commonland": 0
        }
    },
{
        "question": "Tax money should not fund the lifestyles of monarchs or aristocrats.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 10,
            "commonland": 0
        }
    },
{
        "question": "Not everyone should be allowed to make economic decisions.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": -10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Basic utilities should not be left to the market.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "What is produced should not be down to the whims of the market.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 10,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Central banking is best form of banking.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -10,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "A stratified class system is desirable.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": -10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": -10,
            "commonland": 0
        }
    },
{
        "question": "Certain services like roads and public transportation should be run by the state.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -10,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "The Industrial Revolution and its consequences have been a disaster for the human race.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": -10,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Government run industry is superior to existing alternatives.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -10,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Worker's self-management is a good idea.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "There should be no managers with authority over workers.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Workers should not be given too much autonomy or they’ll be lazy.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": -10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "The hiring and firing of workers should not be down to the whims of bosses.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": -10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Independent labor organizations should not be allowed to exist.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": -10,
            "planning": 0,
            "regulation": 10,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Top down structures for organisations work best.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": -10,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "The economy should be organised on the local level.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": -10,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Pop culture is better than local culture.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 10,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Some sexual orientations are to be socially favored.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": -10,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },

{
        "question": "Euthanasia should be legal.",
        "effect": {
            "freedom": 15,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Any sexual activity is fine as long as everyone involved is a consenting adult.",
        "effect": {
            "freedom": 10,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Altering our language to make it more gender-inclusive is not a bad idea.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": 10,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Gender should be abolished.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 10,
            "inclusivity": 5,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "An individual's gender is determined by their chromosomes.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": 0,
            "inclusivity": -10,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "International borders should not exist.",
        "effect": {
            "freedom": 10,
            "power": 10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "We should be skeptical of new technologies.",
        "effect": {
            "freedom": 0,
            "power": 0,
            "culture": -10,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": -5,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Political correctness has gone too far.",
        "effect": {
            "freedom": 10,
            "power": 0,
            "culture": 0,
            "inclusivity": -10,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Free speech should be protected",
        "effect": {
            "freedom": 15,
            "power": 0,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Firearms should be available to the general public.",
        "effect": {
            "freedom": 10,
            "power": 10,
            "culture": 0,
            "inclusivity": 0,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
{
        "question": "Everyone has right to believe in any religion.",
        "effect": {
            "freedom": 10,
            "power": 0,
            "culture": 0,
            "inclusivity": 10,
            "econpower": 0,
            "econglobe": 0,
            "globe": 0,
            "nation": 0,
            "equity": 0,
            "horizontal": 0,
            "planning": 0,
            "regulation": 0,
            "automation": 0,
            "production": 0,
            "merit": 0,
            "commonland": 0
        }
    },
];
